# Generated by Django 2.1.7 on 2020-03-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('citycode', models.CharField(max_length=5)),
                ('cityname', models.CharField(max_length=25, verbose_name='City Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Header_Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=50, verbose_name='Location Code')),
                ('loccode', models.CharField(max_length=7, verbose_name='Location Code')),
                ('gstin_no', models.CharField(max_length=15, verbose_name='GSTIN No')),
                ('pan_no', models.CharField(max_length=10, verbose_name='PAN No')),
                ('locaddress', models.TextField(max_length=200, verbose_name='Operation Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(max_length=20)),
                ('loccity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.City')),
            ],
        ),
        migrations.CreateModel(
            name='LabourCost_State_IndustryWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statecode', models.CharField(max_length=5)),
                ('statename', models.CharField(default='No Data', max_length=50, verbose_name='State Name')),
                ('cityname', models.CharField(default='No Data', max_length=50, verbose_name='City Name')),
                ('statecountry', models.CharField(max_length=30, verbose_name='Country')),
                ('skilled_labour_cost', models.FloatField(default=0.0)),
                ('unskilled_labour_cost', models.FloatField(default=0.0)),
                ('semiskilled_labour_cost', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('industryType', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLocation',
            fields=[
                ('oplocationid', models.IntegerField(primary_key=True, serialize=False)),
                ('betterplace_siteid', models.CharField(default='No ID', max_length=50, verbose_name='Site Id')),
                ('betterplace_sitename', models.CharField(default='No Data', max_length=50, verbose_name='Site Name')),
                ('oploccode', models.CharField(max_length=7, unique=True, verbose_name='Location Code')),
                ('oploclat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('oploclong', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('oplocaddress', models.TextField(max_length=200, verbose_name='Operation Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(max_length=20)),
                ('oploccity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateid', models.IntegerField(primary_key=True, serialize=False)),
                ('statecode', models.CharField(max_length=5)),
                ('statename', models.CharField(max_length=25, verbose_name='State Name')),
                ('statecountry', models.CharField(max_length=30, verbose_name='Country')),
                ('skilled_labour_cost', models.FloatField(default=0.0)),
                ('unskilled_labour_cost', models.FloatField(default=0.0)),
                ('semiskilled_labour_cost', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='invoice_header_location',
            name='locstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='citystate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.State'),
        ),
    ]
