# Generated by Django 2.1.7 on 2020-08-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customermaster_internalorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='CARE_OF',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='CONTCT_PRSN',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='CUST_BLK',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='CUST_CLS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='DIST',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='EXTR_ADRS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='EXTR_BP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='INDSTRY_CODE',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='INDUSTRY',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='LTA_NUM',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='LUT_NUM',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='NAME_2',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='NOT_RELSD',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='PYMT_TRM',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='STREET_4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='STREET_5',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='TAX_CAT',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
