# Generated by Django 2.1.7 on 2020-08-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200803_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalorders',
            name='BUSNS_SEGMNT',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='COST_CNTR',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='CREATED_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='CUSTOMER_ENTITY',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='CUSTOMER_STATE',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='CUST_GRP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='CUST_PAN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='DELVR_ADDRS',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='EVENT',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='GROUP_EXT',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='HARMONY_IO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='IDT_OP_SERVICE_CLASS',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='INDUSTRY',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='LOCATION',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='ORDR_CTGRY',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='ORDR_TYPE',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='PLANT',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='PRM_VERTICAL',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='PRSN_RESPNSBL',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='STATISTICAL',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='STATUS',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='internalorders',
            name='UPDATED_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
