# Generated by Django 2.1.7 on 2020-08-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200803_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdeliveryaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELVR_ADDRS', models.CharField(max_length=10)),
                ('PRIM_ADDRESS', models.CharField(blank=True, max_length=1, null=True)),
                ('INTRNL_ORDR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.InternalOrders')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderdeliveryaddress',
            unique_together={('INTRNL_ORDR', 'DELVR_ADDRS')},
        ),
    ]
