# Generated by Django 2.1.7 on 2020-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdetail',
            name='aadhaar_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
