# Generated by Django 2.1.7 on 2020-03-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contractdetail_aadhaar_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fixedcostrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
